version: '3.8'

services:
  rabbitmq:
    build:
      context: ./docker/rabbitmq
    image: rabbitmq:3.13.1
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"

  celery_worker_broadcast:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    image: celery_worker_broadcast
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672//
      - QUEUE=broadcast
    depends_on:
      - rabbitmq

  celery_worker_direct:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    image: celery_worker_direct
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672//
      - QUEUE=direct
    depends_on:
      - rabbitmq